config/routes.rb
Crowdfunder::Application.routes.draw do

 

  # get "sessions/new"
  # get "sessions/create"
  # get "sessions/destroy"

  root :to => 'welcome#index'

# resources :sessions, only: [:new, :create, :destroy]

# delete "logout" => "sessions#destroy", as: "logout"

# get "login" => "sessions#new", as: "login"
  resources :sessions, :only => [:new, :create, :destroy]
  resources :projects
  resources :users, :except => [:index]
end 

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  attr_accessible :amount
  belongs_to :user
  belongs_to :project
  validates :amount, numericality: {greater_than: 0}
  validates :user, presence: true
  validates :project, presence: true

  end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :goal, :teaser, :title, :user_id
  belongs_to :user
  has_many :pledges
  validates :title, presence: true, length: {maximum: 100}
  validates :teaser, presence: true, length: {maximum: 255}
  validates :description, presence: true
  validates :goal, presence: true, numericality: {greater_than: 0, allow_blank: true}


end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :first_name, :last_name, :email, :password, 
  :password_confirmation

  has_many :projects
  has_many :pledges

  validates :first_name, :last_name, :email, presence: true
  validates :password, presence: true, on: :create
  validates :password, confirmation: true
  
  validates :email, uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  	@projects = Project.all
  end

  def show
  	@project = Project.find(params[:id])
  end

  # def new
  # 	@project = Project.new 
  # end

  # def create
  #   @project = Project.new 
  # end

  # def edit
  # 	@project = Project.find(params[:id])
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	if login(params[:email], params[:password])
  		redirect_back_or_to(root_path, :notice => 'Login Successful')
  	else
  		@user = User.new(params[:user])
  		flash.now[:alert] = "Invalid" 
  		render "new"
    end
 	end
  
  def destroy
  	logout
  	redirect_back_or_to(root_path, :notice => "Bye")
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new params[:user]
  	if @user.save
  		auto_login(@user)
  		redirect_to root_path, :notice => "Account created"
  	else
      flash.now[:notice] = "Try again"
  		render "new"
  	end
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'layouts/shared/nav' %>

    <div class="container">
        <%= yield %>
    </div>

    <% if flash[:notice] %>
   		<%= flash[:notice] %>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert">    
      	 <%= flash[:alert] %>
      </div>
    <% end %>

</body>
</html>

app/views/layouts/shared/_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">CrowdFunder</a>
      <div class="nav-collapse collapse">

        <ul class="nav">
          <li class="<%= 'active' if current_page? root_path %>">
            <%= link_to 'Home', :root %>
          </li>
          <li class="<%= 'active' if current_page? projects_path %>">
            <%= link_to 'Projects', :projects %>
          </li>
            <div class="pull-right">
              <div class="btn btn-success">
               <% if logged_in? %>
                 <%= link_to 'Logout', session_path(current_user), method: :delete, class: 'btn' %>
               <% else %>
                <%= link_to 'Sign Up', [:new, :user], class: 'btn btn-primary' %>
                <%= link_to 'Login', '#', class: 'btn' %>
               <% end %>
             </div>
           </div>
        </ul>

      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>Listing projects</h1>
<% @projects.each do |project| %>
	<%= link_to project.title, project %><br />
<% end %>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
	<%= @project.description %><br />
	<%= @project.goal %><br />
	<%= @project.teaser %><br >
	<%= @project.user.first_name %><br >
	<%= @project.user.last_name %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

	<% unless f.object.errors.empty? %>
	  <div class="alert alert-error">
	    <strong>Try again after fixing the following things:</strong><br/>
	    <ul>
	      <% f.object.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	    </ul>
	  </div>
	<% end %>

	<%= f.label :first_name  %><br />
	<%= f.text_field :first_name  %><br />


	<%= f.label :last_name  %><br />
	<%= f.text_field :last_name  %><br />


	<%= f.label :email  %><br />
	<%= f.text_field :email %><br />


	<%= f.label :password  %><br />
	<%= f.password_field :password  %><br />


	<%= f.label :password_confirmation  %><br />
	<%= f.password_field :password_confirmation  %><br />

	<%= f.submit "Create Account" %>
<% end %>

app/views/users/new.html.erb
<h1>New Users</h1>


<%= render :partial => "form" %>

app/views/welcome/index.html.erb
<h1>Welcome!!!</h1>